CREATE TABLE IF NOT EXISTS POSTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT CLOB(10M) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NULL,
    VIEWS INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS POST_TAGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID BIGINT NOT NULL,
    TAG_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE
);
